endpoint: https://thespacedevs-production.up.railway.app/
transport:
  type: streamable_http
operations:
  source: local
  paths:
    - ./graphql/TheSpaceDevs/operations
schema:
  source: local
  path: ./graphql/TheSpaceDevs/api.graphql
overrides:
  mutation_mode: all
introspection:
  execute:
    enabled: true
  introspect:
    enabled: true
  search:
    enabled: true
  validate:
    enabled: true
cors:
  enabled: true
  allow_any_origin: true
#telemetry:
#  exporters:
#    metrics:
#      otlp:
#        endpoint: "http://127.0.0.1:4317"
#        protocol: "grpc"
#        metadata:
#          api-key: my-super-secret-key
