endpoint: https://thespacedevs-production.up.railway.app/
transport:
  type: streamable_http
operations:
  source: local
  paths:
    - ./graphql/TheSpaceDevs/operations
schema:
  source: local
  path: ./graphql/TheSpaceDevs/api.graphql
overrides:
  mutation_mode: all
introspection:
  execute:
    enabled: true
    hints_file: execute_hints.txt
    # hints: Some inline hints that could be used instead of hints_file
  introspect:
    enabled: true
  search:
    enabled: true
  validate:
    enabled: true
cors:
  enabled: true
  allow_any_origin: true
#telemetry:
#  exporters:
#    metrics:
#      otlp:
#        endpoint: "http://127.0.0.1:4317"
#        protocol: "grpc"
#        metadata:
#          some-key: some-value
