"""
List upcoming rocket launches, soonest first, with rocket, mission, and provider details
"""
query ListUpcomingLaunches {
  upcomingLaunches(limit: 10, ordering: "net") {
    pagination {
      count
    }
    results {
      id
      name
      net
      weatherConcerns
      rocket {
        id
        configuration {
          fullName
        }
      }
      mission {
        name
        description
      }
      webcastLive
      launchServiceProvider {
        name
      }
    }
  }
}
