query PublishedSchemaQuery($graphRef: ID!) {
    variant(ref: $graphRef) {
        __typename
        ... on GraphVariant {
            latestPublication {
                schema {
                    hash
                    document
                }
            }
        }
        ... on InvalidRefFormat {
            message
        }
    }
}

query PublishedSchemaHashQuery($graphRef: ID!) {
    variant(ref: $graphRef) {
        __typename
        ... on GraphVariant {
            latestPublication {
                schema {
                    hash
                }
            }
        }
        ... on InvalidRefFormat {
            message
        }
    }
}
