type Agency {
  id: Int!
  url: String
  name: String!
  abbrev: String
  type: AgencyType
  featured: Boolean
  country: [Country]
  description: String
  administrator: String
  foundingYear: Int
  launchers: String
  spacecraft: String
  parent: String
  image: Image
  logo: Image
  socialLogo: Image
  totalLaunchCount: Int
  consecutiveSuccessfulLaunches: Int
  successfulLaunches: Int
  failedLaunches: Int
  pendingLaunches: Int
  consecutiveSuccessfulLandings: Int
  successfulLandings: Int
  failedLandings: Int
  attemptedLandings: Int
  infoUrl: String
  wikiUrl: String
  socialMediaLinks: [SocialMediaLink]
}

type AgencyList {
  pagination: PaginationInfo
  results: [Agency]
}

type AgencyType {
  id: Int!
  name: String
}

type ApiThrottle {
  yourRequestLimit: Int!
  limitFrequencySecs: Int!
  currentUse: Int!
  nextUseSecs: Int!
  ident: String!
}

type Astronaut {
  id: Int!
  url: String
  name: String!
  status: AstronautStatus
  agency: Agency
  image: Image
  type: AstronautType
  inSpace: Boolean
  timeInSpace: String
  evaTime: String
  age: Int
  dateOfBirth: String
  dateOfDeath: String
  nationality: [Country]
  bio: String
  wiki: String
  lastFlight: String
  firstFlight: String
  socialMediaLinks: [SocialMediaLink]
  flightsCount: Int
  landingsCount: Int
  spacewalksCount: Int
}

type AstronautFlight {
  id: Int!
  role: AstronautRole
  astronaut: Astronaut
}

type AstronautList {
  pagination: PaginationInfo
  results: [Astronaut]
}

type AstronautRole {
  id: Int!
  role: String!
  priority: Int
}

type AstronautStatus {
  id: Int!
  name: String!
}

type AstronautType {
  id: Int!
  name: String!
}

type CelestialBody {
  id: Int!
  name: String!
  type: CelestialBodyType
  diameter: Float
  mass: Float
  gravity: Float
  lengthOfDay: String
  atmosphere: Boolean
  image: Image
  description: String
  wikiUrl: String
  totalAttemptedLaunches: Int
  successfulLaunches: Int
  failedLaunches: Int
  totalAttemptedLandings: Int
  successfulLandings: Int
  failedLandings: Int
}

type CelestialBodyList {
  pagination: PaginationInfo
  results: [CelestialBody]
}

type CelestialBodyType {
  id: Int!
  name: String
}

type Country {
  id: Int!
  name: String!
  alpha2Code: String
  alpha3Code: String
  nationalityName: String
  nationalityNameComposed: String
}

type DockingEvent {
  id: Int!
  url: String
  launchId: String
  docking: String
  departure: String
  dockingLocation: DockingLocation
  flightVehicle: SpacecraftFlight
  spaceStation: SpaceStation
}

type DockingEventList {
  pagination: PaginationInfo
  results: [DockingEvent]
}

type DockingLocation {
  id: Int!
  name: String
  spaceStation: SpaceStation
}

type Event {
  id: Int!
  url: String
  slug: String
  name: String!
  type: EventType
  description: String
  webcastLive: Boolean
  location: String
  newsUrl: String
  videoUrl: String
  date: String
  duration: String
  image: Image
  launches: [Launch]
  expeditions: [Expedition]
  spaceStations: [SpaceStation]
  programs: [Program]
}

type EventList {
  pagination: PaginationInfo
  results: [Event]
}

type EventType {
  id: Int!
  name: String!
}

type Expedition {
  id: Int!
  url: String
  name: String!
  start: String
  end: String
  spaceStation: SpaceStation
  crew: [AstronautFlight]
  missionPatches: [MissionPatch]
}

type ExpeditionList {
  pagination: PaginationInfo
  results: [Expedition]
}

type FirstStageType {
  id: Int!
  name: String
}

type Image {
  id: Int
  name: String
  imageUrl: String
  thumbnailUrl: String
}

type ImageLicense {
  id: Int!
  name: String!
  link: String
}

type InfoUrl {
  priority: Int
  source: String
  title: String
  description: String
  featureImage: String
  url: String
}

type Landing {
  id: Int!
  attempt: Boolean
  success: Boolean
  description: String
  downrangeDistance: Float
  location: LandingLocation
  type: LandingType
}

type LandingList {
  pagination: PaginationInfo
  results: [Landing]
}

type LandingLocation {
  id: Int!
  name: String
  abbrev: String
  description: String
  successfulLandings: Int
  attemptedLandings: Int
}

type LandingType {
  id: Int!
  name: String
  abbrev: String
  description: String
}

type Language {
  id: Int!
  name: String!
  code: String
}

type Launch {
  id: String!
  url: String
  slug: String
  name: String!
  status: LaunchStatus
  netPrecision: NetPrecision
  lastUpdated: String
  net: String
  windowEnd: String
  windowStart: String
  holdReason: String
  failReason: String
  probability: Int
  weatherConcerns: String
  hashtag: String
  launchServiceProvider: Agency
  rocket: Rocket
  mission: Mission
  pad: Pad
  webcastLive: Boolean
  image: Image
  infoUrls: [InfoUrl]
  vidUrls: [VidUrl]
  programs: [Program]
}

type Launcher {
  id: Int!
  url: String
  details: String
  serialNumber: String
  status: LauncherStatus
  launcherConfig: LauncherConfiguration
  flights: Int
  lastLaunchDate: String
  firstLaunchDate: String
  image: Image
}

type LauncherConfiguration {
  id: Int!
  url: String
  name: String!
  description: String
  manufacturer: Agency
  family: LauncherConfigurationFamily
  fullName: String
  variant: String
  alias: String
  minStage: Int
  maxStage: Int
  length: Float
  diameter: Float
  maidenFlight: String
  launchMass: Int
  leoCapacity: Int
  gtoCapacity: Int
  toThrust: Int
  apogee: Int
  vehicleRange: Int
  totalLaunchCount: Int
  consecutiveSuccessfulLaunches: Int
  successfulLaunches: Int
  failedLaunches: Int
  pendingLaunches: Int
  attemptedLandings: Int
  successfulLandings: Int
  failedLandings: Int
  consecutiveSuccessfulLandings: Int
  reusable: Boolean
  infoUrl: String
  wikiUrl: String
  image: Image
}

type LauncherConfigurationFamily {
  id: Int!
  name: String!
}

type LauncherConfigurationFamilyList {
  pagination: PaginationInfo
  results: [LauncherConfigurationFamily]
}

type LauncherConfigurationList {
  pagination: PaginationInfo
  results: [LauncherConfiguration]
}

type LauncherList {
  pagination: PaginationInfo
  results: [Launcher]
}

type LauncherStatus {
  id: Int!
  name: String
}

type LaunchList {
  pagination: PaginationInfo
  results: [Launch]
}

type LaunchStatus {
  id: Int!
  name: String!
  abbrev: String
  description: String
}

type Location {
  id: Int!
  url: String
  name: String!
  celestialBody: CelestialBody
  active: Boolean
  countryCode: String
  description: String
  image: Image
  mapImage: String
  timezone: String
  totalLaunchCount: Int
  totalLandingCount: Int
}

type LocationList {
  pagination: PaginationInfo
  results: [Location]
}

type Mission {
  id: Int!
  name: String
  description: String
  launchDesignator: String
  type: MissionType
  orbit: Orbit
}

type MissionPatch {
  id: Int!
  name: String
  priority: Int
  imageUrl: String
}

type MissionPatchList {
  pagination: PaginationInfo
  results: [MissionPatch]
}

type MissionType {
  id: Int!
  name: String!
}

type NetPrecision {
  id: Int!
  name: String!
  abbrev: String
  description: String
}

type NoticeType {
  id: Int!
  name: String!
}

type Orbit {
  id: Int!
  name: String!
  abbrev: String
}

type Pad {
  id: Int!
  url: String
  name: String!
  description: String
  active: Boolean
  infoUrl: String
  wikiUrl: String
  mapUrl: String
  mapImage: String
  latitude: String
  longitude: String
  location: Location
  country: String
  totalLaunchCount: Int
  orbitalLaunchAttemptCount: Int
  fastestTurnaround: String
  image: Image
}

type PadList {
  pagination: PaginationInfo
  results: [Pad]
}

type PaginationInfo {
  count: Int
  next: String
  previous: String
}

type Payload {
  id: Int!
  name: String!
  description: String
  type: PayloadType
  orbit: Orbit
  mass: Float
  dimension: String
  manufacturer: Agency
  owner: Agency
}

type PayloadFlight {
  id: Int!
  payload: Payload
  launch: Launch
  transporter: String
  status: String
}

type PayloadFlightList {
  pagination: PaginationInfo
  results: [PayloadFlight]
}

type PayloadList {
  pagination: PaginationInfo
  results: [Payload]
}

type PayloadType {
  id: Int!
  name: String!
}

type Program {
  id: Int!
  url: String
  name: String!
  description: String
  type: ProgramType
  image: Image
  startDate: String
  endDate: String
  infoUrl: String
  wikiUrl: String
  agencies: [Agency]
  missionPatches: [MissionPatch]
}

type ProgramList {
  pagination: PaginationInfo
  results: [Program]
}

type ProgramType {
  id: Int!
  name: String!
}

type Query {
  agencies(limit: Int, offset: Int, search: String, ordering: String, abbrev: String, name: String, featured: Boolean, countryCode: String): AgencyList
  agency(id: Int!): Agency
  astronauts(limit: Int, offset: Int, search: String, ordering: String, nationality: String, inSpace: Boolean, hasFlown: Boolean): AstronautList
  astronaut(id: Int!): Astronaut
  celestialBodies(limit: Int, offset: Int, search: String, ordering: String): CelestialBodyList
  celestialBody(id: Int!): CelestialBody
  locations(limit: Int, offset: Int, search: String, ordering: String): LocationList
  location(id: Int!): Location
  pads(limit: Int, offset: Int, search: String, ordering: String): PadList
  pad(id: Int!): Pad
  launches(limit: Int, offset: Int, search: String, ordering: String, status: Int, lsp: Int): LaunchList
  upcomingLaunches(limit: Int, offset: Int, search: String, ordering: String, status: Int, lsp: Int): LaunchList
  previousLaunches(limit: Int, offset: Int, search: String, ordering: String, status: Int, lsp: Int): LaunchList
  launch(id: String!): Launch
  events(limit: Int, offset: Int, search: String, ordering: String, type: Int): EventList
  upcomingEvents(limit: Int, offset: Int, search: String, ordering: String, type: Int): EventList
  previousEvents(limit: Int, offset: Int, search: String, ordering: String, type: Int): EventList
  event(id: Int!): Event
  launcherConfigurations(limit: Int, offset: Int, search: String, ordering: String): LauncherConfigurationList
  launcherConfiguration(id: Int!): LauncherConfiguration
  launcherConfigurationFamilies(limit: Int, offset: Int, search: String): LauncherConfigurationFamilyList
  launchers(limit: Int, offset: Int, search: String, ordering: String): LauncherList
  launcher(id: Int!): Launcher
  landings(limit: Int, offset: Int, ordering: String): LandingList
  landing(id: Int!): Landing
  spaceStations(limit: Int, offset: Int, search: String, ordering: String): SpaceStationList
  spaceStation(id: Int!): SpaceStation
  expeditions(limit: Int, offset: Int, search: String, ordering: String): ExpeditionList
  expedition(id: Int!): Expedition
  dockingEvents(limit: Int, offset: Int, ordering: String): DockingEventList
  dockingEvent(id: Int!): DockingEvent
  spacecraftConfigurations(limit: Int, offset: Int, search: String): SpacecraftConfigurationList
  spacecraftConfiguration(id: Int!): SpacecraftConfiguration
  spacecraftConfigurationFamilies(limit: Int, offset: Int, search: String): SpacecraftConfigurationFamilyList
  spacecraft(limit: Int, offset: Int, search: String): SpacecraftList
  spacecraftById(id: Int!): Spacecraft
  spacecraftFlights(limit: Int, offset: Int): SpacecraftFlightList
  spacecraftFlight(id: Int!): SpacecraftFlight
  spacewalks(limit: Int, offset: Int, search: String, ordering: String): SpacewalkList
  spacewalk(id: Int!): Spacewalk
  programs(limit: Int, offset: Int, search: String): ProgramList
  program(id: Int!): Program
  payloads(limit: Int, offset: Int, search: String): PayloadList
  payload(id: Int!): Payload
  payloadFlights(limit: Int, offset: Int): PayloadFlightList
  missionPatches(limit: Int, offset: Int, search: String): MissionPatchList
  missionPatch(id: Int!): MissionPatch
  updates(limit: Int, offset: Int): UpdateList
  apiThrottle: [ApiThrottle]
  agencyTypes(limit: Int, offset: Int): [AgencyType]
  astronautStatuses(limit: Int, offset: Int): [AstronautStatus]
  astronautRoles(limit: Int, offset: Int): [AstronautRole]
  astronautTypes(limit: Int, offset: Int): [AstronautType]
  celestialBodyTypes(limit: Int, offset: Int): [CelestialBodyType]
  countries(limit: Int, offset: Int): [Country]
  dockingLocations(limit: Int, offset: Int): [DockingLocation]
  eventTypes(limit: Int, offset: Int): [EventType]
  firstStageTypes(limit: Int, offset: Int): [FirstStageType]
  imageLicenses(limit: Int, offset: Int): [ImageLicense]
  landingLocations(limit: Int, offset: Int): [LandingLocation]
  landingTypes(limit: Int, offset: Int): [LandingType]
  languages(limit: Int, offset: Int): [Language]
  launchStatuses(limit: Int, offset: Int): [LaunchStatus]
  launcherStatuses(limit: Int, offset: Int): [LauncherStatus]
  missionTypes(limit: Int, offset: Int): [MissionType]
  netPrecisions(limit: Int, offset: Int): [NetPrecision]
  noticeTypes(limit: Int, offset: Int): [NoticeType]
  orbits(limit: Int, offset: Int): [Orbit]
  payloadTypes(limit: Int, offset: Int): [PayloadType]
  programTypes(limit: Int, offset: Int): [ProgramType]
  roadClosureStatuses(limit: Int, offset: Int): [RoadClosureStatus]
  spaceStationStatuses(limit: Int, offset: Int): [SpaceStationStatus]
  spacecraftConfigurationTypes(limit: Int, offset: Int): [SpacecraftConfigurationType]
  spacecraftStatuses(limit: Int, offset: Int): [SpacecraftStatus]
}

type RoadClosureStatus {
  id: Int!
  name: String!
}

type Rocket {
  id: Int!
  configuration: LauncherConfiguration
}

type SocialMediaLink {
  id: Int
  url: String
  socialMediaSite: String
}

type Spacecraft {
  id: Int!
  url: String
  name: String!
  status: SpacecraftStatus
  description: String
  serialNumber: String
  spacecraftConfig: SpacecraftConfiguration
}

type SpacecraftConfiguration {
  id: Int!
  url: String
  name: String!
  type: SpacecraftConfigurationType
  manufacturer: Agency
  inUse: Boolean
  capability: String
  history: String
  details: String
  maidenFlight: String
  height: Float
  diameter: Float
  humanRated: Boolean
  crewCapacity: Int
  payloadCapacity: Int
  payloadReturnCapacity: Int
  flightLife: String
  imageUrl: String
  wikiLink: String
  infoLink: String
}

type SpacecraftConfigurationFamily {
  id: Int!
  name: String!
}

type SpacecraftConfigurationFamilyList {
  pagination: PaginationInfo
  results: [SpacecraftConfigurationFamily]
}

type SpacecraftConfigurationList {
  pagination: PaginationInfo
  results: [SpacecraftConfiguration]
}

type SpacecraftConfigurationType {
  id: Int!
  name: String!
}

type SpacecraftFlight {
  id: Int!
  url: String
  destination: String
  missionEnd: String
  spacecraft: Spacecraft
  launch: Launch
  launchCrew: [AstronautFlight]
  onboardCrew: [AstronautFlight]
  landingCrew: [AstronautFlight]
}

type SpacecraftFlightList {
  pagination: PaginationInfo
  results: [SpacecraftFlight]
}

type SpacecraftList {
  pagination: PaginationInfo
  results: [Spacecraft]
}

type SpacecraftStatus {
  id: Int!
  name: String!
}

type SpaceStation {
  id: Int!
  url: String
  name: String!
  status: SpaceStationStatus
  stationType: SpaceStationStatus
  orbit: String
  founded: String
  deorbited: String
  height: Float
  width: Float
  mass: Float
  volume: Int
  description: String
  owners: [Agency]
  onboardCrew: Int
  image: Image
}

type SpaceStationList {
  pagination: PaginationInfo
  results: [SpaceStation]
}

type SpaceStationStatus {
  id: Int!
  name: String!
}

type Spacewalk {
  id: Int!
  url: String
  name: String
  start: String
  end: String
  duration: String
  location: String
  crew: [AstronautFlight]
  spaceStation: SpaceStation
}

type SpacewalkList {
  pagination: PaginationInfo
  results: [Spacewalk]
}

type UpdateEntry {
  id: Int!
  profileImage: String
  comment: String
  infoUrl: String
  createdBy: String
  createdOn: String
}

type UpdateList {
  pagination: PaginationInfo
  results: [UpdateEntry]
}

type VidUrl {
  priority: Int
  source: String
  publisher: String
  title: String
  description: String
  featureImage: String
  url: String
}

"""Exposes a URL that specifies the behavior of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behavior of this scalar."""
  url: String!,
) on SCALAR

directive @defer(label: String, if: Boolean! = true) on FRAGMENT_SPREAD | INLINE_FRAGMENT

