name: Prepare Release

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Configure Git
        run: |
          git config --global user.name GitHub Actions
          git config user.email github-actions@github.com

      - uses: knope-dev/action@v2.1.0
        with:
          version: 0.22.1

      - run: knope prepare-release --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label release PR
        run: gh pr edit --add-label release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
